name: firmware

# For now, this workflow is used for checks, not for releases.
# So all release stuff is commented out.

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request: {}

permissions:
  contents: write

jobs:
  keira:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # or 'true' for non-recursive
          fetch-depth: 0         # fetch full history, required for submodules to work properly
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ./.pio
          key: ${{ runner.os }}-keira
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build and package firmware
        run: |
          mkdir -p out
          if [[ "$(git branch --show-current)" == "main" ]]; then
            for lang in $(cat languages.txt); do
              echo "Building for $lang"
              PLATFORMIO_BUILD_FLAGS=-D$lang pio run -e v2
              cp .pio/build/v2/firmware.bin out/keira_${lang}.bin
              cp .pio/build/v2/partitions.bin out/partitions.bin
              cp .pio/build/v2/bootloader.bin out/bootloader.bin
              pip install esptool
              esptool.py --chip esp32s3 merge_bin \
                -o out/KeiraOS_merged_${lang}.bin \
                0x0 out/bootloader.bin \
                0x8000 out/partitions.bin \
                0x10000 out/keira_${lang}.bin
            done
          else
            echo "Building for default language"
            pio run -e v2
            cp .pio/build/v2/firmware.bin out/keira.bin
            cp .pio/build/v2/partitions.bin out/partitions.bin
            cp .pio/build/v2/bootloader.bin out/bootloader.bin
            pip install esptool
            esptool.py --chip esp32s3 merge_bin \
              -o out/KeiraOS_merged.bin \
              0x0 out/bootloader.bin \
              0x8000 out/partitions.bin \
              0x10000 out/keira.bin
          fi

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KeiraOS-firmware
          path: out/*.bin

      - name: Upload KeiraOS bins to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/*.bin
